#!/usr/bin/env python

"""
setup.py file for PyNEC Python module

Author Tim Molteno. tim@molteno.net
"""

import distutils.sysconfig
import os
from glob import glob

import numpy as np
import setuptools

# Remove silly flags from the compilation to avoid warnings.
# cfg_vars = distutils.sysconfig.get_config_vars()
# for key, value in cfg_vars.items():
#  if type(value) == str:
#    cfg_vars[key] = value.replace("-Wstrict-prototypes", "")

# Generate a list of the sources.
nec_sources = []
nec_sources.extend(
    [
        fn
        for fn in glob("necpp_src/src/*.cpp")
        if not os.path.basename(fn).endswith("_tb.cpp")
        if not os.path.basename(fn).startswith("net_solve.cpp")
        if not os.path.basename(fn).startswith("nec2cpp.cpp")
        if not os.path.basename(fn).startswith("necDiff.cpp")
    ]
)
nec_sources.extend(glob("PyNEC_wrap.cxx"))

nec_headers = []
nec_headers.extend(glob("necpp_src/src/*.h"))
nec_headers.extend(glob("necpp_src/config.h"))


# Backend selection. Default: ATLAS clapack (serial). Set PYNEC_BACKEND=
#   atlas   -> ATLAS clapack via libatlas-base-dev (serial; reference baseline)
#   lapacke -> reference LAPACKE + OpenBLAS pthread (threaded)
#   mkl     -> MKL LAPACKE + MKL gnu_thread (libgomp)
#   mkl_intel -> MKL LAPACKE + MKL intel_thread (libiomp5, Intel's OpenMP)
# The config.h file is generated by running ./configure in necpp_src; pass
# --with-lapack to enable the LAPACK code path.
_backend = os.environ.get("PYNEC_BACKEND", "atlas").lower()
_extra_include = []
_extra_link_dirs = []
# -fopenmp enables the #pragma omp directives in necpp's matrix-fill code.
# We always want it on (it's cheap if no pragmas are present), and it's
# required by the MKL gnu_thread layer anyway.
_extra_compile = ["-fPIC", "-fopenmp"]
if _backend == "lapacke":
    _link_args = ["-lstdc++", "-fopenmp", "-llapacke", "-lopenblas"]
    _defines = [("LAPACK", "1"), ("LAPACKE", "1")]
elif _backend in ("mkl", "mkl_intel"):
    _mkl_root = os.environ.get("MKLROOT", "/opt/intel/oneapi/mkl/latest")
    _extra_include = [f"{_mkl_root}/include"]
    _extra_link_dirs = [f"{_mkl_root}/lib"]
    if _backend == "mkl_intel":
        _iomp_root = os.environ.get(
            "IOMP_ROOT", "/opt/intel/oneapi/compiler/latest/lib"
        )
        _extra_link_dirs.append(_iomp_root)
        _link_args = [
            "-lstdc++",
            f"-Wl,-rpath,{_mkl_root}/lib",
            f"-Wl,-rpath,{_iomp_root}",
            "-lmkl_intel_lp64",
            "-lmkl_intel_thread",
            "-lmkl_core",
            "-liomp5",
            "-lpthread",
            "-lm",
            "-ldl",
        ]
    else:
        # gcc + libgomp threading, lp64 indexing.
        _link_args = [
            "-lstdc++",
            f"-Wl,-rpath,{_mkl_root}/lib",
            "-lmkl_intel_lp64",
            "-lmkl_gnu_thread",
            "-lmkl_core",
            "-lgomp",
            "-lpthread",
            "-lm",
            "-ldl",
        ]
        _extra_compile.append("-fopenmp")
    _defines = [("LAPACK", "1"), ("LAPACKE", "1"), ("USE_MKL", "1")]
elif _backend in ("openblas_pypi", "scipy_openblas"):
    # OpenBLAS provided by the scipy-openblas32 PyPI wheel (LP64 / 32-bit int,
    # matching PyNEC's lapack_int = int). This is the redistributable-wheel
    # backend: the same mechanism works on Linux and Windows, needs no system
    # BLAS packages, and auditwheel/delvewheel bundle the shipped
    # libscipy_openblas into the wheel.
    #
    # scipy-openblas is built with -DBLAS_SYMBOL_PREFIX=scipy_, so every BLAS /
    # LAPACKE symbol is prefixed (libscipy_openblas exports scipy_LAPACKE_*).
    # Its bundled <lapacke.h> declares the prefixed prototypes, so remap the two
    # LAPACKE entry points matrix_algebra.cpp calls to the prefixed names; the
    # call sites then resolve to the declared prototypes and the exported
    # symbols. (zgetrf_work / zgetrs_work are the only LAPACKE symbols PyNEC
    # uses — see matrix_algebra.cpp lu_decompose_lapack / solve_lapack.)
    import scipy_openblas32 as _ob

    _extra_include = [_ob.get_include_dir()]
    _extra_link_dirs = [_ob.get_lib_dir()]
    _link_args = [
        "-lstdc++",
        "-fopenmp",
        f"-l{_ob.get_library()}",  # "scipy_openblas"
        # rpath so a locally-built (non-auditwheel) extension finds the lib;
        # harmless in a repaired wheel, where the lib is vendored alongside.
        f"-Wl,-rpath,{_ob.get_lib_dir()}",
    ]
    _defines = [
        ("LAPACK", "1"),
        ("LAPACKE", "1"),
        ("LAPACKE_zgetrf_work", "scipy_LAPACKE_zgetrf_work"),
        ("LAPACKE_zgetrs_work", "scipy_LAPACKE_zgetrs_work"),
    ]
else:
    _link_args = ["-lstdc++", "-llapack_atlas", "-llapack", "-lcblas", "-latlas"]
    _defines = []

necpp_module = setuptools.Extension(
    "_PyNEC",
    sources=nec_sources,
    include_dirs=[
        np.get_include(),
        "necpp_src/src",
        "necpp_src/",
        "necpp_src/win32/",
        "/usr/include/x86_64-linux-gnu",
        *_extra_include,
    ],
    library_dirs=_extra_link_dirs,
    extra_compile_args=_extra_compile,
    extra_link_args=_link_args,
    depends=nec_headers,
    define_macros=[
        ("BUILD_PYTHON", "1"),
        ("NPY_NO_DEPRECATED_API", "NPY_1_7_API_VERSION"),
        *_defines,
    ],
)

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="PyNEC",
    version="1.7.4",
    author="Tim Molteno",
    author_email="tim@physics.otago.ac.nz",
    url="http://github.com/tmolteno/python-necpp",
    keywords="nec2 nec2++ antenna electromagnetism radio",
    description="Python Antenna Simulation Module (nec2++) object-oriented interface",
    long_description=long_description,
    long_description_content_type="text/markdown",
    include_package_data=True,
    data_files=[("examples", ["example/test_rp.py"])],
    ext_modules=[necpp_module],
    requires=["numpy"],
    py_modules=["PyNEC"],
    license="GPLv2",
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Topic :: Scientific/Engineering",
        "Topic :: Communications :: Ham Radio",
        "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
        "Programming Language :: Python :: 3",
        "Intended Audience :: Science/Research",
    ],
)
