#!/usr/bin/env python

"""
setup.py file for PyNEC Python module

Author Tim Molteno. tim@molteno.net
"""

import distutils.sysconfig
import os
import sys
from glob import glob

import numpy as np
import setuptools

# Remove silly flags from the compilation to avoid warnings.
# cfg_vars = distutils.sysconfig.get_config_vars()
# for key, value in cfg_vars.items():
#  if type(value) == str:
#    cfg_vars[key] = value.replace("-Wstrict-prototypes", "")

# Generate a list of the sources.
nec_sources = []
nec_sources.extend(
    [
        fn
        for fn in glob("necpp_src/src/*.cpp")
        if not os.path.basename(fn).endswith("_tb.cpp")
        if not os.path.basename(fn).startswith("net_solve.cpp")
        if not os.path.basename(fn).startswith("nec2cpp.cpp")
        if not os.path.basename(fn).startswith("necDiff.cpp")
    ]
)
nec_sources.extend(glob("PyNEC_wrap.cxx"))

nec_headers = []
nec_headers.extend(glob("necpp_src/src/*.h"))
nec_headers.extend(glob("necpp_src/config.h"))


# Backend selection. Default: ATLAS clapack (serial). Set PYNEC_BACKEND=
#   atlas   -> ATLAS clapack via libatlas-base-dev (serial; reference baseline)
#   lapacke -> reference LAPACKE + OpenBLAS pthread (threaded)
#   mkl     -> MKL LAPACKE + MKL gnu_thread (libgomp)
#   mkl_intel -> MKL LAPACKE + MKL intel_thread (libiomp5, Intel's OpenMP)
# The config.h file is generated by running ./configure in necpp_src; pass
# --with-lapack to enable the LAPACK code path.
_backend = os.environ.get("PYNEC_BACKEND", "atlas").lower()
_extra_include = []
_extra_link_dirs = []
# Linked libraries by name (used by the MSVC path; the GCC paths pass -l<name>
# through extra_link_args instead).
_libraries = []
# -fopenmp enables the #pragma omp directives in necpp's matrix-fill code.
# We always want it on (it's cheap if no pragmas are present), and it's
# required by the MKL gnu_thread layer anyway.
_extra_compile = ["-fPIC", "-fopenmp"]
if _backend == "lapacke":
    _link_args = ["-lstdc++", "-fopenmp", "-llapacke", "-lopenblas"]
    _defines = [("LAPACK", "1"), ("LAPACKE", "1")]
elif _backend in ("mkl", "mkl_intel"):
    _mkl_root = os.environ.get("MKLROOT", "/opt/intel/oneapi/mkl/latest")
    _extra_include = [f"{_mkl_root}/include"]
    _extra_link_dirs = [f"{_mkl_root}/lib"]
    if _backend == "mkl_intel":
        _iomp_root = os.environ.get(
            "IOMP_ROOT", "/opt/intel/oneapi/compiler/latest/lib"
        )
        _extra_link_dirs.append(_iomp_root)
        _link_args = [
            "-lstdc++",
            f"-Wl,-rpath,{_mkl_root}/lib",
            f"-Wl,-rpath,{_iomp_root}",
            "-lmkl_intel_lp64",
            "-lmkl_intel_thread",
            "-lmkl_core",
            "-liomp5",
            "-lpthread",
            "-lm",
            "-ldl",
        ]
    else:
        # gcc + libgomp threading, lp64 indexing.
        _link_args = [
            "-lstdc++",
            f"-Wl,-rpath,{_mkl_root}/lib",
            "-lmkl_intel_lp64",
            "-lmkl_gnu_thread",
            "-lmkl_core",
            "-lgomp",
            "-lpthread",
            "-lm",
            "-ldl",
        ]
        _extra_compile.append("-fopenmp")
    _defines = [("LAPACK", "1"), ("LAPACKE", "1"), ("USE_MKL", "1")]
elif _backend in ("openblas_pypi", "scipy_openblas"):
    # OpenBLAS provided by the scipy-openblas32 PyPI wheel (LP64 / 32-bit int,
    # matching PyNEC's lapack_int = int). This is the redistributable-wheel
    # backend: the same mechanism works on Linux and Windows, needs no system
    # BLAS packages, and auditwheel/delvewheel bundle the shipped
    # libscipy_openblas into the wheel.
    #
    # scipy-openblas is built with -DBLAS_SYMBOL_PREFIX=scipy_, so every BLAS /
    # LAPACKE symbol is prefixed (libscipy_openblas exports scipy_LAPACKE_*).
    # Its bundled <lapacke.h> declares the prefixed prototypes, so remap the two
    # LAPACKE entry points matrix_algebra.cpp calls to the prefixed names; the
    # call sites then resolve to the declared prototypes and the exported
    # symbols. (zgetrf_work / zgetrs_work are the only LAPACKE symbols PyNEC
    # uses — see matrix_algebra.cpp lu_decompose_lapack / solve_lapack.)
    import scipy_openblas32 as _ob

    _extra_include = [_ob.get_include_dir()]
    _extra_link_dirs = [_ob.get_lib_dir()]
    _defines = [
        ("LAPACK", "1"),
        ("LAPACKE", "1"),
        ("LAPACKE_zgetrf_work", "scipy_LAPACKE_zgetrf_work"),
        ("LAPACKE_zgetrs_work", "scipy_LAPACKE_zgetrs_work"),
    ]
    if sys.platform == "win32":
        # MSVC build. Classic /openmp (OpenMP 2.0) suffices — necpp's omp loops
        # use signed int indices with no collapse/simd. Force-include
        # msvc_compat.h to neutralize the GCC-only
        # __attribute__((tls_model("initial-exec"))) in necpp. /bigobj because
        # the amalgamated NEC2++ translation units are large. Link
        # scipy-openblas's import library (scipy_openblas.lib); delvewheel
        # vendors the DLL into the wheel.
        _here = os.path.dirname(os.path.abspath(__file__))
        _extra_include.append(_here)
        _extra_compile = ["/openmp", "/EHsc", "/bigobj", "/FImsvc_compat.h"]
        _libraries = [_ob.get_library()]  # scipy_openblas -> scipy_openblas.lib
        _link_args = []
    elif sys.platform == "darwin":
        # macOS (Apple Silicon). Apple clang ships no OpenMP runtime, so use
        # Homebrew libomp: -Xpreprocessor -fopenmp to honor the #pragma omp
        # directives, plus libomp's include/lib. LIBOMP_PREFIX is exported by
        # cibuildwheel (see pyproject [tool.cibuildwheel.macos]); fall back to
        # the arm64 Homebrew prefix. No -lstdc++: clang links libc++
        # automatically for C++ sources (-lstdc++ does not exist on macOS).
        # delocate vendors libscipy_openblas + libomp into the wheel.
        _libomp = os.environ.get("LIBOMP_PREFIX", "/opt/homebrew/opt/libomp")
        _extra_include.append(os.path.join(_libomp, "include"))
        # -std=c++17: Apple clang defaults to an older C++ standard, so necpp's
        # `thread_local` (C++11) is rejected without this. The Linux gcc default
        # is already new enough, hence no -std on that branch.
        _extra_compile = ["-fPIC", "-std=c++17", "-Xpreprocessor", "-fopenmp"]
        _link_args = [
            f"-L{os.path.join(_libomp, 'lib')}",
            "-lomp",
            f"-l{_ob.get_library()}",  # "scipy_openblas"
            # rpaths so a locally-built (non-delocated) extension finds the libs;
            # harmless in a repaired wheel, where they are vendored alongside.
            f"-Wl,-rpath,{_ob.get_lib_dir()}",
            f"-Wl,-rpath,{os.path.join(_libomp, 'lib')}",
        ]
    else:
        _extra_compile = ["-fPIC", "-fopenmp"]
        _link_args = [
            "-lstdc++",
            "-fopenmp",
            f"-l{_ob.get_library()}",  # "scipy_openblas"
            # rpath so a locally-built (non-auditwheel) extension finds the lib;
            # harmless in a repaired wheel, where the lib is vendored alongside.
            f"-Wl,-rpath,{_ob.get_lib_dir()}",
        ]
else:
    _link_args = ["-lstdc++", "-llapack_atlas", "-llapack", "-lcblas", "-latlas"]
    _defines = []

necpp_module = setuptools.Extension(
    "_PyNEC",
    sources=nec_sources,
    include_dirs=[
        np.get_include(),
        "necpp_src/src",
        "necpp_src/",
        "necpp_src/win32/",
        "/usr/include/x86_64-linux-gnu",
        *_extra_include,
    ],
    library_dirs=_extra_link_dirs,
    libraries=_libraries,
    extra_compile_args=_extra_compile,
    extra_link_args=_link_args,
    depends=nec_headers,
    define_macros=[
        ("BUILD_PYTHON", "1"),
        ("NPY_NO_DEPRECATED_API", "NPY_1_7_API_VERSION"),
        *_defines,
    ],
)

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    # Distribution name for the accelerated fork. Kept distinct from upstream
    # "PyNEC" (owned by tmolteno on PyPI/TestPyPI) so this fork can publish to a
    # package index. The *import* name is unchanged — `import PyNEC` still works;
    # only `pip install pynec-accel` differs.
    name="pynec-accel",
    # 1.7.4.postN were same-source repackages of upstream 1.7.4 — only the wheel
    # build changed:
    #   post1: stop vendoring libgomp on Linux (static-TLS collision).
    #   post2: stop vendoring libomp on macOS (delocate --exclude libomp) so it
    #          shares one OpenMP runtime with momwire — fixes OMP Error #15 /
    #          deadlock on cross-engine runs. Needs `brew install libomp`.
    # 1.7.5 is the first fork release that changes the NEC2++/wrapper *source*:
    # c_geometry gains a public set_intersection_check(bool) knob (wrapped for
    # Python) so callers can disable the fatal wire/segment intersection
    # validator and match NEC-2 / nec2c permissiveness on closely-spaced /
    # crossing wires. A minor bump, not a post-release, because it adds public
    # API.
    version="1.7.6",
    author="Tim Molteno",
    author_email="tim@physics.otago.ac.nz",
    url="https://github.com/stevenmburns/python-necpp",
    keywords="nec2 nec2++ antenna electromagnetism radio",
    description="PyNEC accelerated fork (OpenBLAS + OpenMP) — nec2++ object-oriented interface",
    long_description=long_description,
    long_description_content_type="text/markdown",
    include_package_data=True,
    data_files=[("examples", ["example/test_rp.py"])],
    ext_modules=[necpp_module],
    # install_requires (not the dead distutils `requires`) so the wheel
    # actually declares its runtime numpy dependency — the SWIG wrapper imports
    # numpy, so an install without it fails at `import PyNEC`.
    install_requires=["numpy"],
    py_modules=["PyNEC"],
    license="GPLv2",
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Topic :: Scientific/Engineering",
        "Topic :: Communications :: Ham Radio",
        "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
        "Programming Language :: Python :: 3",
        "Intended Audience :: Science/Research",
    ],
)
